### PR TITLE
Update Chinese translation

### PR DESCRIPTION
**Pull request by GodGun968**

### CODE REVIEW

**Comment by isXander** [comment]
More translations are needed from the latest pushes.

**Comment by GodGun968** [comment]
Can you give me the latest compiled jar to verify Chinese translation,If not my translation may not be very accurate

**Comment by isXander** [comment]
All language files are available here, on GitHub!

**Comment by GodGun968** [comment]
yes,but I need to translate with the actual effect

**Comment by isXander** [comment]
You can get them from the actions tab. Download the artifact and extract

**Comment by GodGun968** [comment]
oh,thanks,New Chinese translation coming soon

**Comment by GodGun968** [comment]
Right,I In your other works have also submitted translation,remember to merge

**Comment by GodGun968** [comment]
ok

**Comment by GodGun968** [comment]
ok

**Pull request merged**
